import type { Metadata } from "next";
import "./globals.css";
import Auth0Provider from "@/components/Wrappers/Auth0Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Auth0Provider>
        <body className={`antialiased`}>{children}</body>
      </Auth0Provider>
    </html>
  );
}
